name: state_machine
version: 2.2.11
publish_to: none
description: Finite state machine library. Easily define legal state transitions.
    Listen to state entrances, departures, and transitions.
homepage: https://github.com/Workiva/state_machine

environment:
    sdk: '>=2.12.0 <3.0.0'

dependencies:
    w_common:
        git:
            url: https://github.com/amerchDev/w_common
            ref: master
            path: w_common/

dev_dependencies:
    build_runner: ^2.3.3
    build_web_compilers: ^3.2.7
    dart_style: ^2.2.4
    test: ^1.23.1
